### ISSUE TITLE
Proposal: Fork p4est and libsc

### ISSUE THREAD

**Issue by jmark** [DLR-AMR/t8code#1018]
t8code depends on p4est and libsc. They are included via the git submodule mechanism.

From time to time, we need to push fixes upstream to p4est or libsc in order to maintain compatibility with latest developments in t8code.

In order to be a bit more independent and speed up our development process, I propose to fork both libraries into the DLR-AMR github project and link t8code against these forks.

We can push our changes to libsc and p4est to these forks, test them properly and if they proven their worth can be pushed as PRs to the original repositories.

**Comment by cburstedde** [comment]
I understand that you may be prompted to do this. It may however be the first step of a serious divergence that might become ever harder to fix in the future. Since we guarantee that the p4est history never moves backwards, what would speak against working through PRs against the official p4est history as previously?

I can only guess that you're missing the sc_MPI_INT8 type that we have removed to work with a relatively ancient MPI standard. Would it not be sufficient to #define sc_MPI_INT8 sc_MPI_BYTE in a toplevel t8code .h file to get it all to work?

Happy to discuss further!
