### ISSUE TITLE
"UNKNOWN" heading in documentation

### ISSUE THREAD

**Issue by jwallwork23** [DLR-AMR/t8code#1160]
The title on page https://dlr-amr.github.io/t8code/doc/v2.0.0/index.html is "t8", followed by "UNKNOWN". Similarly for other versions and "latest". However, on the https://dlr-amr.github.io/t8code/doc/dev/index.html page there is a version number here (`2.0.0.496-6683`). Is there an issue with the pages for versions other than "dev"?

(Part of JOSS review https://github.com/openjournals/joss-reviews/issues/6887.)

**Comment by holke** [comment]
@jwallwork23 thank you for reporting.

This is a duplicate of https://github.com/DLR-AMR/t8code/issues/1070.
Basically there was an issue in our CI that generates the documentation that resulted in the version not being visible.

The issue is resolved and upcoming versions will have the  correct version number.

**Comment by jwallwork23** [comment]
Okay great, thanks! In that case I'll close the issue.
