### ISSUE TITLE
Check behavior of while-loop in recursive coarsening function in forest_adapt.cxx

### ISSUE THREAD

**Issue by Flo1314** [DLR-AMR/t8code#214]
Consider the adaptation of a forest F1 to a forest F2. 

If `refine_recursive` has been applied to an element E_i in F1 (to build its children in F2) and afterwards, `coarsen_recursive` is applied to an element E_j with j>i, then the while-loop in `coarsen_recursvie` may not be triggered, leading to 'artifacts' in the resulting mesh F2 (see attached pictures).

Whats going on? After `refine_recursive`, `el_coarsen = el_inserted + num_children;` is set. Now, consider recursive coarsening of the next element in F1: there, the while loop demands `pos >= el_coarsen`, where `pos = el_inserted - num_children`. This will not be true, if el_inserted has not been updated after el_coarsen has been set.

  => no while loop in coarsen_recursive => no recursive coarsening of the element E_j

If we move on in F1, then at some point el_inserted will be updated and be large enough, such that coarsen_recursive will 'automatically' work again.

(I also uploaded some notes that roughly describe the issue - [Artifacts.pdf](https://github.com/holke/t8code/files/8513811/Artifacts.pdf))

![Artifacts](https://user-images.githubusercontent.com/64836791/164035340-2d5352d6-79a8-4348-8a8d-ae68ea343de6.png)
![Artifacts_Testcase_F1](https://user-images.githubusercontent.com/64836791/164035346-cde1a5a4-9944-4eaf-9e02-d0b63da65d5b.png)
![Artifacts_Testcase_F2](https://user-images.githubusercontent.com/64836791/164035351-7ceab26a-2598-4e16-8b54-70173a08e76b.png)

**Comment by holke** [comment]
Thank you for creating this issue!
Great explanation with the pictures and all.

**Comment by holke** [comment]
When we adress this we should also cover this in a test case.

**Comment by ililikakis** [comment]
The branch fix-issue_214 should fix the problem. 
@Flo1314  Would you test it again with your expanding circle or make available to me?
It works now in a small example, similar to the one in your PDF.

**Comment by Flo1314** [comment]
![oneproc_ts1](https://user-images.githubusercontent.com/64836791/216946858-93033bc0-72dd-4f98-99cb-d9b1a2ce08bb.png)
![oneproc_ts2](https://user-images.githubusercontent.com/64836791/216946865-9229d95c-cf87-46fb-a944-33e894458b85.png)

**Comment by Flo1314** [comment]
Computed on four procs

![fourprocs_ts1](https://user-images.githubusercontent.com/64836791/216946967-29903eb5-1cba-430d-9890-34c9fed920ef.png)
![fourprocs_ts2](https://user-images.githubusercontent.com/64836791/216946976-0f9c1ba4-b899-4115-a132-c5af00b003d6.png)

**Comment by Flo1314** [comment]
![fourprocs_ts2_color](https://user-images.githubusercontent.com/64836791/216947490-2478a015-118e-4d42-9500-d77d9f51b1f5.png)

**Comment by ililikakis** [comment]
My small example works fine with the fix, also in parallel. 
Could you color the first output of the computation on four procs, too?

**Comment by Flo1314** [comment]
These are the VTKs for the sequential and parallel run:
[VTK.zip](https://github.com/DLR-AMR/t8code/files/10662710/VTK.zip)

**Comment by Flo1314** [comment]
These are the VTKs for the sequential run and the parallel run:
[VTK.zip](https://github.com/DLR-AMR/t8code/files/10662756/VTK.zip)

I hope this helps, otherwise let me know.

**Comment by ililikakis** [comment]
That is even better, thanks!

**Comment by Flo1314** [comment]
The circular example can also be found in the feature_subelements branch, in example/transition/t8_transition_global.cxx

You could copy this function into your branch, but it would be necessary to delete some subelement specific funcitons that are not known to your branch. If you consider this option, just let me know and I can try to help.

**Comment by ililikakis** [comment]
I have now found time to take a closer look at your rather large example.

The "hotfix" you put in really fixed a bug descript in your first comment. So running your code with the fix on one process results in artifact-free forests. I will make a PR soon to include the fix in the main branch.

But why are the artifacts still showing up in your example with multiple processors? This is due to the process boundaries. If you take a closer look at two consecutive forests `F_{i-1}` and `F_{i}` in ParaView and color the elements according to the ranks, you might see it. The coordinates of artifacts in `F_{i}` are the same as those of elements at some process boundary of `F_{i-1}`.

The problem with coarsening at process boundaries is that a process may only see part of a family, and in this case, it does not coarse.

After each of your (adaption) steps, you re-partition your forest. Thus, artifacts produced in forest `F_{i}` from adapting `F_{i-i}` disappear in `F_{i+1}` if they are no longer on a process boundary in `F_{i}` after partitioning.

I hope this was understandable.

**Comment by Flo1314** [comment]
Thanks, this is a great and detailed explanation!

But the artifact-on-multiple-processors problem should still be existent in the main branch even after your fix, right? Or is it a problem of how I set up my specific example?

**Comment by ililikakis** [comment]
Yes exactly, your artifact problem on several processes remains for the time being. The problem comes from the design of the function `t8_forest_adapt.cxx`. However, there are two other issues #132 and #33, if both are successfully resolved, that should solve your problem as well. 
Until then I can only offer you a workaround in your example:
At this [line ](https://github.com/DLR-AMR/t8code/blob/feature_subelements/example/transition/t8_transition_global.cxx#L484 ) you can adapt your forest again by adding lines
```C++
// ....
/* clean forest from artifacts */
forest = forest_adapt;
t8_forest_init (&forest_adapt);
t8_forest_set_user_data (forest_adapt, &ls_data);
t8_forest_set_adapt (forest_adapt, forest, t8_adapt_clean_artifacts, 1);
if (set_balance) {
  t8_forest_set_balance (forest_adapt, forest, 0);
}
if (do_ghost) {
  t8_forest_set_ghost_ext (forest_adapt, do_ghost, T8_GHOST_FACES, ghost_version);
}
if (do_partition) {
  t8_forest_set_partition (forest_adapt, forest, 0);
}
t8_forest_commit (forest_adapt);
// ...
```
and callback funktion 
```C++
int
t8_adapt_clean_artifacts (t8_forest_t forest,
                          t8_forest_t forest_from,
                          t8_locidx_t which_tree,
                          t8_locidx_t lelement_id,
                          t8_eclass_scheme_c *ts,
                          const int is_family,
                          const int num_elements, t8_element_t *elements[])
{
  t8_example_level_set_struct_t *ls_data =
    (t8_example_level_set_struct_t *) t8_forest_get_user_data (forest);
  t8_basic_sphere_data_t *sdata = (t8_basic_sphere_data_t *) ls_data->udata;

  const double       *s_midpoint = sdata->mid_point;
  double              elem_midpoint[3];
  t8_forest_element_centroid (forest_from, which_tree, elements[0], elem_midpoint);
  const double        dist = t8_vec_dist (s_midpoint, elem_midpoint);
  const int           level = ts->t8_element_level (elements[0]);
  
  if (is_family && level > ls_data->min_level && dist < sdata->radius - 0.05) {
    return -1;
  }
  return 0;
}
```
This removes some artifacts as the forest is repartitioned after each adaptation. 

You also can do this several times
```C++
do {
    /* clean forest from artifacts */
} while (!t8_forest_is_equal (forest, forest_adapt));
```

**Comment by Flo1314** [comment]
Alright, got it. Thanks for the great detective work and these tips! ;)
