### ISSUE TITLE
Documentation of `t8_element_tree_face` is incomplete.

### ISSUE THREAD

**Issue by jmark** [DLR-AMR/t8code#365]
The following doc-string to `t8_element_tree_face` does not make sense ...

```
/** Given an element and a face of this element. If the face lies on the
 *  tree boundary, return the face number of the tree face.
 *  If not the return value is arbitrary.
 * \param [in] ts       Implementation of a class scheme.
 * \param [in] elem     The element.
 * \param [in] face     The index of a face of \a elem.
 * \return The index of the tree face that \a face is a subface of, if
 *         \a face is on a tree boundary.
 *         Any arbitrary integer if \a is not at a tree boundary.
 */
int                 t8_element_tree_face (t8_eclass_scheme_c *ts,
                                          const t8_element_t *elem, int face);

// resp.

  /** Given an element and a face of this element. If the face lies on the
   *  tree boundary, return the face number of the tree face.
   *  If not the return value is arbitrary.
   * \param [in] elem     The element.
   * \param [in] face     The index of a face of \a elem.
   * \return The index of the tree face that \a face is a subface of, if
   *         \a face is on a tree boundary.
   *         Any arbitrary integer if \a is not at a tree boundary.
   */
  virtual int         t8_element_tree_face (const t8_element_t *elem,
                                            int face) = 0;
```

The actual implementations seem also rather unexpected:
```
int
t8_default_scheme_hex_c::t8_element_tree_face (const t8_element_t *elem,
                                               int face)
{
  T8_ASSERT (t8_element_is_valid (elem));
  T8_ASSERT (0 <= face && face < P8EST_FACES);
  /* For hexahedra the face and the tree face number are the same. */
  return face;
}

// or

int
t8_dtri_tree_face (t8_dtri_t *t, int face)
{
  T8_ASSERT (0 <= face && face < T8_DTRI_FACES);
  /* TODO: Assert if boundary */

// ...
}
```

**Comment by Davknapp** [comment]
Regarding the description:
Which part does not make sense?

Regarding the implementation:
For hexahedra that share a face with its tree/root-element, the labeling of the faces coincide, similar for prisms. The labels coincide, because the children of an element are not rotated versions of the parent and for most (I think all should be true too, but I don't know it by heart) default implementations the children in the corner of an element even have the same type.  I don't know, what is meant by "Assert if boundary". We return an arbitrary integer, if the element does not lay on the boundary, therefore the implementation is still correct if an element not sharing a face with its tree.

**Comment by jmark** [comment]
Hmm ... let us focus on the documentation first:
```Given an element and a face of this element. If the face lies on the
 tree boundary, return the face number of the tree face.
 If not the return value is arbitrary.```

For an hexaeder I would expect the following behavior:
```
If the element touches the tree boundary it returns the same
face number which was given as argument. This can only
be numbers between 0 and 5.

If it does not touch a tree boundary then what? Arbitrary
number? This could also include 0 to 5.
```
How can I, the user, reliably distinguish between these cases?

**Comment by holke** [comment]
Checking whether an element is on the tree boundary can be rather expensive while computing the face number is (often) very cheap.
The quad example shows this quite clearly: If i am at the boundary, i know that the tree face number is just the face number of the element.
No further computation needed.

Hence, we do not want to include the check whether this element is at the boundary, but outsource it, so that it is only called when explicitely needed.

This check can be performed with `t8_element_is_root_boundary`

So the intended usage is:

1. Be sure that the element lies at the root boundary (either by calling `t8_element_is_root_boundary` oder by knowing from other context)
2. Call `t8_element_tree_face`

Or 

1. Call `t8_element_tree_face`
2. Ensure that the element is at the boundary before using the result.


I understand  that the documentation is misleading and should at least include a hint to `t8_element_is_root_boundary`

**Comment by holke** [comment]
Please checkout my PR for this.
Is it now clearer?
